### ISSUE TITLE
Create writer class for markdown files

### ISSUE THREAD

**Issue by mogres** [mesoscope/cellpack#135]
## Use Case
Currently, markdown files for analysis reports are created within the analysis class. It would be useful to have a generic markdown writer class for this.

https://github.com/mesoscope/cellpack/pull/78#discussion_r1095216907

## Solution
Create a `MarkDownWriter` class to handle markdown files.

**Comment by meganrm** [comment]
it would be nice if from Analysis.py we could call something like MarkdownWrite.write(header=HEADER, body=BODY)
