### ISSUE TITLE
Create an ingredient type/feature that allows for size distribution 

### ISSUE THREAD

**Issue by meganrm** [mesoscope/cellpack#178]
## Use Case
Peroxisomes have variable radii

## Solution
Be able to set a distribution for an ingredient radius

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by mogres** [comment]
We can approach this similar to the variable count distribution. 

The `validate_ingredient_info` function in `Ingredient.py` handles the variable count. We can add an if statement to check for options related to variable size. 

Things to consider: 

- Size of the grid is set by the size of the smallest ingredient. We will need to think about how to handle this.
- Not all types of ingredient have the same parameters for size. (Length vs radius, etc.)

**Comment by mogres** [comment]
`update_variable_ingredient_attributes` should probably be called before grid creation so that the size of ingredients can determine the grid spacing if needed.

**Comment by mogres** [comment]
It might be helpful to create a grid with the smallest size possible from the input distribution, 

1. Uniform distribution: minimum value
2. Gaussian distribution: mean - std_dev
3. list: minimum value in the list

**Comment by mogres** [comment]
Closed in #193
