### ISSUE TITLE
standardize results file names

### ISSUE THREAD

**Issue by meganrm** [mesoscope/cellpack#180]
## Use Case
right now if we run pack with a config file that has `save_analyze_result` turned on the file names start with `results_seed_0...`
but if we run without `save_analyze_result` then the file names are different

## Solution
no matter what the files names should include 
1. recipe name
2. recipe version 
3. config file name 
4. seed number 

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by mogres** [comment]
The `Analysis` function can run multiple seeds simultaneously in parallel, and adds the `seed_`  prefix to the name of the result file on line 2216 of `Analysis.py`. We can check whether more than one seed is being packed before adding this prefix.
Here is the line that adds this: 
`seed_basename = f"seed_{seed_index}_{packing_basename}"`

**Comment by mogres** [comment]
`save_as_simularium` takes in an input for the `result_file_path`. We also pass in the `env` which has its own `env.result_file`. We should keep these consistent with one another.
