### ISSUE TITLE
delete expired S3 metadata in firebase

### ISSUE THREAD

**Issue by rugeli** [mesoscope/cellpack#195]
## Use Case
*Please provide a use case to help us understand your request in context*
To avoid unnecessary costs, we want to delete result files from our S3 bucket that older than 6 months 

## Solution
*Please describe your ideal solution*
set up a github action that runs periodically to identify and remove old files

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by meganrm** [comment]
run it once a month
