### ISSUE TITLE
Proposal: defaulting S3 metadata uploads to staging database

### ISSUE THREAD

**Issue by rugeli** [mesoscope/cellpack#233]
## Use Case
*Please provide a use case to help us understand your request in context*
When executing the `pack` command, the current workflow requires a choice between dev and staging databases for saving S3 metadata. This increases manual intervention and may lead to potential issues, such as #229 

## Solution
*Please describe your ideal solution*
Given that we will be periodically cleaning expired S3 metadata specifically from the staging database, it's logical to direct all S3 metadata to the staging database by default. 

This change will eliminate manual input for database selection during the processing of non-firebase recipe packings. For firebase- related packings, like `upload -r [LOCAL-RECIPE]` or `pack -r [FIREBASE-RECIPE]`, choosing the db to incorporate with will still be required.   

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*
Open to suggestions

**Comment by mogres** [comment]
This sounds like a good idea! Thanks for creating the issue to track it.
