### ISSUE TITLE
Cannot pack firebase recipes due to missing "composition" key

### ISSUE THREAD

**Issue by mogres** [mesoscope/cellpack#245]
## Description
On the main branch, packing a firebase recipe results in an error. Here are the steps I followed:

### Local recipe works as expected
![image](https://github.com/mesoscope/cellpack/assets/101426188/99ad5f7a-464c-4375-aac6-b1a98bc57f99)

### Recipe is available on firebase
![image](https://github.com/mesoscope/cellpack/assets/101426188/440d52ab-490a-4b9e-ba7b-35be0a8539a9)

### Packing the recipe from firebase results in an error
![image](https://github.com/mesoscope/cellpack/assets/101426188/e9ccd8fc-d239-4932-a512-988fea23fff1)

## Expected Behavior
The firebase recipe should run similar to the local recipe

**Comment by rugeli** [comment]
Thank you for reporting this bug! I acciderntally deleted the line that calls the path validation function within `load_file()` in `cellpack/autopack/__init__.py`. I will make a one-line pr and add it back. 

expected behaviors are in this merged pr #230
