### ISSUE TITLE
Cache python installation in github actions

### ISSUE THREAD

**Issue by mogres** [mesoscope/cellpack#249]
## Use Case
Python installation takes a long time while running our tests through github actions. We can cache the python version and update as needed to speed up the workflows.

Refer [here](https://github.com/aics-int/nuc-morph-analysis/pull/378) for an example.

More information on caching [here](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)

## Solution
Add `cache: true` in the install dependencies step

**Comment by pgarrison** [comment]
Note: the linked change in `nuc-morph-analysis` was for a `pdm` setup. Since cellpack uses pip, you'll need a different solution, maybe something like [this](https://github.blog/changelog/2021-11-23-github-actions-setup-python-now-supports-dependency-caching/)
