### ISSUE TITLE
Text debt/maintenance on cellPack analysis repo.

### ISSUE THREAD

**Issue by meganrm** [mesoscope/cellpack#263]
Done when we have a pipeline that re-creates the peroxisomes analysis results. In addition to cellPACK make sure other deps are available publicly.  Update the README to make other people able to use the pipelines.
Track the actual issue:

https://github.com/mesoscope/cellpack-analysis/issues/13

**Comment by meganrm** [comment]
UPDATE: made good progress, may need space on s3 to store data (check with devOps if the space is ok to use)

**Comment by mogres** [comment]
@kvegesna was able to run the peroxisome analysis pipeline from a fresh install on an EC2 instance using local files. Next steps in will involve running individual steps of the pipeline on the cloud.
