### ISSUE TITLE
Do true distance to cube surface calculation 

### ISSUE THREAD

**Issue by meganrm** [mesoscope/cellpack#40]
## Use Case
Cubes should be able to sit edge to edge, which isn't possible if you're using an encapsulating radius to detect collisions 

## Solution
Calculate the distance to the cube surface instead of the sphere surface in jitter collision detection 

## Alternatives
*Please describe any alternatives you've considered, even if you've dismissed them*

**Comment by mogres** [comment]
Issue closed in PR #44
