### ISSUE TITLE
Format version with sub-versions is not compatible with the migration

### ISSUE THREAD

**Issue by mogres** [mesoscope/cellpack#85]
## Description
Using a recipe with format version `2.0.0` returns an empty recipe

## Expected Behavior
Recipes with format sub-versions `2.0.x` should not be migrated (if migration is not necessary)

**Comment by meganrm** [comment]
We made the decision that we weren't going to need 3 units of precision for format versions. but then didn't update the recipes. So I think the fix here is just changing the format_version in the recipes instead of changing the code. We could add a check incase someone types it incorrectly

**Comment by mogres** [comment]
Sounds good, I have updated the recipes I was using. Closing this now.
