### ISSUE TITLE
Save converted recipe as a `.json` in the `out` folder

### ISSUE THREAD

**Issue by meganrm** [mesoscope/cellpack#88]
## Use Case
It would be good to have old recipes converted into the new file format

## Solution

Write a function in the recipe loader that is called by `migrate`.

After conversion programmatically save the converted recipe_data as a `[RECIPE-NAME]-v2.json`

the `out` folder is defined in the config, for example: `https://github.com/mesoscope/cellpack/blob/main/packing-configs/run.json`

**Comment by meganrm** [comment]
https://www.geeksforgeeks.org/reading-and-writing-json-to-a-file-in-python/

**Comment by rugeli** [comment]
- [ ] save converted recipe to the specified output folder in the config file
